# Generated by Django 6.0.5 on 2026-05-13 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admindashboard', '0002_book_about_author_book_amazon_link_book_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='borrwedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateField(auto_now_add=True, verbose_name='Borrowed Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('returned', models.BooleanField(default=False, verbose_name='Returned Status')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindashboard.book', verbose_name='Borrowed Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Borrower')),
            ],
            options={
                'verbose_name': 'Borrowed Book',
                'verbose_name_plural': 'Borrowed Books',
                'ordering': ['-borrowed_date'],
            },
        ),
    ]
