# Generated by Django 6.0.5 on 2026-05-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Book Title')),
                ('author', models.CharField(max_length=255, verbose_name='Author')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release Date')),
                ('language', models.CharField(default='English', max_length=50, verbose_name='Language')),
                ('cover', models.ImageField(default='default.jpg', upload_to='covers/', verbose_name='Cover Image')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-id'],
            },
        ),
    ]
