# Generated by Django 6.0.5 on 2026-05-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='about_author',
            field=models.URLField(blank=True, null=True, verbose_name='About Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='amazon_link',
            field=models.URLField(blank=True, null=True, verbose_name='Amazon Link'),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(max_length=255, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Release Date'),
        ),
    ]
